### PR TITLE
5.2.4-administration-manual

### PR DESCRIPTION
**Pull request by thabaum**
Updates more docs, removes/moves pages and sections for future updates.

### CODE REVIEW

**Review by thabaum — COMMENTED** [review]
More hoping going updates into this branch?

**Review by thabaum — COMMENTED** [review]
hoping this adds manual/installation files along with all the other updates

**Comment by thabaum** [comment]
I got a lot more updates, but I am still learning how to deal with the most simple tasks.  This VS Code and GitHub make the most geekiest jobs out of the most simplest... it is why no one wants to help here I am sure.

I have a lot of changes from yesterday and today, not showing up here... stupid why they are not as I should just be able to push them all here.  I have no clue what made it and what did not... so I will go through and manually upload/edit files like normal to ensure I have the latest updates in this PR i guess... if I have time today, or attempt it again tomorrow.

**Comment by thabaum** [comment]
Yahoo! found out what I was doing or not doing to get things based off changes in VS Code, and apply new changes to my branch.  This one is pretty massive, I will keep working on things now that I have this caught up so you can merge tonight!

**Comment by thabaum** [comment]
@iJungleboy Done for the night... you can merge what you can or wait until tomorrow... I will finish up the Admin Management section then hopefully... file management was pretty big update. I am hoping the rest don't take as long but I do need to do SIte Settings next.

Just an FYI, I will keep this coming everyday until this and all my issues are closed best I can.  If you merge this tonight I will create another branch to work on and start fresh.

**Comment by thabaum** [comment]
Any link issues I will fix later as well as double check things each pass through, I just can't seem to build it yet.  I will get there, should not be any as I can see in the view and I do test all links as I work along, I just may typo something so getting a second eyes on things is helpful.

I will update some of the file names as my naming convention gets more under control for the different image types.  I think once this is all done up, you all can complete them or clean them up as needed.  

Call this stage 1 of the docs rocket 
# 🚀

**Comment by iJungleboy** [comment]
@thabaum I think you working style is still a bit bumpy ;). 

For example, it's not normal to have 100+ commits just for some text changes, so I have no Idea how you're doing it, but we should have a look at this. My guess is a few tips on git & vs-code should make the ride smoother.

**Comment by thabaum** [comment]
@iJungleboy I am working out the kinks... I just wanted to make a few adjustments before you merged to make the flow right for each page in the event I cannot get to this for a while.  So that last commit was a "test" to burn for me working with VS Code and Git if you are referring to it.  The previous git changes where much larger with a lot of files, and again just testing working with it live here.

Now that I have it down I can actually do a number of files, or just one quick edit and push a PR up here using VS and Git.

All the commits before that I don't understand how but came from me pushing up the PR initially from Codespaces, which actually pushed every change I made as a commit, where using "Git" makes just one commit.

**Comment by thabaum** [comment]
@iJungleboy the huge number of commits came from using GitHub extension:

image

not "git"

**Comment by thabaum** [comment]
@iJungleboy I fixed some links in the Guides - Modules section as I had not had time to review everything broken on that change.  I think all the other areas have good working links now.

This section needs a lot of love, I wont get to it this week I do not think.  I am going to focus on the Admin Management today and take a break.  This is where I have pushed a lot of images already.

The modules guide I need to compare to the current modules manual sections to see what overlaps and where links can be added to pretty much say the same thing and/or remove them entirely.

The guides can go more into details, I am just trying to put core usage in the manuals section and guides how to use them further in the guides section.

I put an image of each feature at the top which I like, but can go below the introduction as well... we can talk more at next meeting as needed.  I will try to get all the pages looking/feeling the same today in the Manuals section so this is completed for now.

Next time I can allocate time I will work closer with the guides section if I can't complete it as well today.  This last commit fixes all the link issues in the modules section.  I will review the others for broken links/images missing as well.

**Comment by thabaum** [comment]
@iJungleboy looks like the guides/themes section can use some love to merge what you had created and what was previously in the manual section.

I think a "theme development" and "working with themes" TOC should work out and be sure to merge all these guides as needed to not overlap content already discussed.

maybe you can pull this off? There is an index-old.md file and toc-old.yml that should really be merged somehow into an "Overview"

I was using "Overview" for the guides index pages and "Introduction" for the manuals section.  The manual more or less introduces all the features, while the guides give a more larger scope of topics if that makes sense.

So in the "Overview" can lead to your "Introduction" to developing modules guide and also an "Introduction" to working with or an "Overview as well.  Same can be done with the "Modules" guides so they are flowing in the same way to anyone using these areas to get familiar with more details on how to work with all the added different features Oqtane has more broken down into these guides if that makes sense.

**Comment by thabaum** [comment]
to keep more simple i just put "Introduction" all index pages in TOC.

I am also making some adjustments to the guides to a point to include them all but I will let you make any final adjustments in this area so I can focus on admin management manuals today.

**Comment by thabaum** [comment]
@iJungleboy last commit just kind of brings things closer together... I see "Modules" and "Themes" both as "Extensions" so I believe next meeting we can discuss how we can improve our "Guides" section further.  I am hoping all links and TOC are fixed well enough to get by for now.

My next commit will be for all the admin pages I will try to get done by tonight and call it good until our next meeting.

**Comment by thabaum** [comment]
@iJungleboy I might do some more later, but this gets all images on pages and a general layout for all the manuals and guides.

I will improve upon this tomorrow, but you can merge this I believe and it would be worth fixing any noticeable links, but I will provide more content in a later PR very soon.

This should be worthy of merging now.

Thank you.

**Comment by thabaum** [comment]
@iJungleboy I will review this now.  It may have a  few broken links from pages I have not removed that maybe still in the branch I wasn't sure to remove yet to pull content from.  I will work on building this and reviewing all the errors to confirm.  The pages I worked on should all be in TOC.

**Comment by thabaum** [comment]
@iJungleboy i downloaded the current master to test for build warnings and see them, issue is, these are not updated files and are missing a lot of updates I thought had been pushed up.

It has been a bit of a nightmare working with "Codespaces" as I have seen a lot of work disappear I swore I did already I am having to do again....

**Pull request merged**
