### PR TITLE
Spelling and typo fixes for multiple docs pages

### PR DESCRIPTION
**Pull request by digitaldirk**
Fixed/reworded sentence

### CODE REVIEW

**Comment by digitaldirk** [comment]
@dotnet-policy-service agree

**Comment by thabaum** [comment]
@digitaldirk Hi, thank you for the contribution! 
You Rock! 🎸

**Comment by thabaum** [comment]
@digitaldirk FYI: We had a documentation meeting today and we discussed grouping as many smaller fixes like this together in 1 PR.  I am just letting you know so that if you find any further spelling errors you can just continue to add them here in this PR until this gets merged.

**Comment by digitaldirk** [comment]
@thabaum Okay, I have a few more I found so I will add them here.

**Comment by digitaldirk** [comment]
I am now done with my changes. Unless there are more changes required from the discussion below:

I saw some pages have "personilizable", I think the better spelling would be "personalizable" but that is not a word (personalize is a word though). So a instead of i after the n.

@thabaum

**Comment by thabaum** [comment]
@digitaldirk thank you!

**Comment by thabaum** [comment]
@digitaldirk if you can go ahead and update the last issue you noticed that would be great!  So far everything looks like it should merge fine.

**Comment by digitaldirk** [comment]
Done making changes to this PR

**Comment by thabaum** [comment]
@digitaldirk Awesome and thanks again!  Again until this gets merged you can continue to add any additional small fixes like these to this PR.  

@iJungleboy The maintainer is asleep by now.  He will be pretty excited when he wakes up to see this contribution coming from a new contributor. Welcome aboard!

All changes so far look good after reviewing!

Nice work!

**Comment by thabaum** [comment]
https://github.com/oqtane/oqtane.docs/pull/17/files
#17 had a number of fixes like this that could be reviewed to see if any more can get included as well.

This pull request along with any remaining changes in the pull request I had submitted prior I do not think were addressed yet in #17 can help us close #19 for now until after 5.1 docs release.  

@iJungleboy Maybe we can put up a more general long term issue for spelling corrections as a community chore tagged issue?  Include some simple instructions on what can be done from time to time or as you stumble across one.  I feel with a few watch dogs in this area of typos will be limited.

**Pull request merged**
