### PR TITLE
5.2.4 Documentation Update

### PR DESCRIPTION
**Pull request by thabaum**
_DRAFT_ (updated 11/2/2024)

# Administration Manual 5.2.4 Update

## Introduction
The administration pages have needed updates for some time.  Oqtane version 6.0.0 is on deck so this is a final push for the 5.x.x version to catch things up to where the Oqtane Framework administration manual documents are heading.

### What's Included
- Updates new images to reflect the latest UI updates
- Reorganizes folders and table of contents
- Adds missing administration features
- Updates content, admin and host management features
- Naming convention of feature-name-image-type used for all assets

#### To Do
Shift things to guides and keep the manual more "core focused" on functionality and general usage.  Add cross-links with "See Also" sections at the bottom along with a more familiar .NET developer layout.

## Additional Info
Working on updating all the latest images and UI documentation information needed to present a fully documented Oqtane Framework management manual.

Also will work on providing links to the next sections at the bottom similar to: https://docs.oqtane.org/manuals/admin/themes/theme-configuration.html

Since these sections are already created I will just make a placeholder that pushes them to these sections possibly, however I think the management part should be put in each section, and then rename those TOC "Modules" to "Developing Modules" and "Developing Themes" which should probably be moved to our "Guides" section.

We can link the management pages to the guides, as this is where we should be showing people how to do things, while the manual just shows what features are a part of the system.  We should review this part a little more.

In fact some of it should be in the "Content Management " sections as well.

I also see stuff in the Marketplace that can be moved probably to the Guides section as well as some will be covered in Host Administration.

Since this is a huge undertaking and hard to communicate I will provide this PR working from "Content Management" to "Admin Management" then to "Host Management" to ensure everything I currently provided screenshots for is covered in those areas which will move a lot out of these other sections making them unnecessary.  Then anything else can be moved to the "Guides" sections such as developing modules/themes and more in depth use of the Marketplace.

In fact I think "How to restart Oqtane" should be a "Guide" as well which points to the page section in host management that will cover this topic.

Once this transformation is complete I believe it will be much easier for anyone to contribute to documentation.  I will even provide a guide on how I am doing this 100% using GitHub only.

One other point to make is how we discussed how complicated the "installations" section looks and would like to make it more simplified I believe?

I think we can move all the current installation docs to the "Guides" section and put a basic installation with links going to the guides to make the manual simpler and cleaner as well.   I will review this option to see if anything makes sense and include that once I get the rest of this completed.

Please dont be afraid to speak up if anything does not sound right or can be improved upon.  This is going to be a complete facelift going forward, I am not holding back until we get the organization of documentation completed in a way we can easily add to it without confusion and any issues discussed along with those in our issues reported are all resolved from our meetings.

I will be accepting donations :)

### CODE REVIEW

**Comment by thabaum** [comment]
```
---

## Control Panel Walkthrough

### Accessing the Language Management Feature

1. Click the control panel icon to access additional settings.

   ![Control Panel Icon](assets/control-panel-button.jpg)

2. In the control panel, select the button to open the admin dashboard.

   ![Open Admin Dashboard](assets/control-panel-admin-dashboard-button.jpg)

3. In the admin dashboard, click on the Language Management icon to configure your language resources.

   ![Admin Dashboard Language Management](assets/admin-dashboard-language-management.jpg)

---
```

I was going to make this an "include" file maybe @iJungleboy it's a good idea?

@GregStevenson Just change the `   Admin Dashboard Language Management` to reflect the section you are working on and this all can get included in your PR's to keep things flowing the same for each administration feature.

Any thoughts?

**Comment by thabaum** [comment]
@iJungleboy I am going to make another push today, in fact after reviewing things I think I can get the entire thing done by tonight so @GregStevenson unless you have something to push and share now please wait for this PR to be completed.

I am going to remove the current sections and rename things as follows:

The lines will be replaced with as follows:

- Installation
- Content Management
- Admin Management
- Host Management
- Modules
- Themes
- Marketplace
- How To Restart Oqtane ?!?! should be in "Host Management" right? so may move this...

image

@sbwalker before I get too crazy with all these menu updates I hope this makes sense to you as well?

**Comment by thabaum** [comment]
Images are loaded in assets folders, old stuff that makes no sense with the new stuff mostly removed but more around I will cleanup as I go through sections... and all the changes made to main files and TOC to get started updating each section rapidly.

I used a naming convention on the images to follow each manual section topic so it would be nice if we can try to follow it down the road if new images are needed so we can find the ones that relate easily.

**Comment by iJungleboy** [comment]
So first thanks for the many changes @thabaum

I've merged them, but there are problems.

It appears that you probably never built this, so there are a lot of issues like missing menus etc. 
So many of the pages you contributed are nowhere to be found. 

So I'll open a new issue for you to finish this.

**Pull request merged**
